name: music-segmentation-env
channels:
  - conda-forge
  - defaults
dependencies:
  - python=3.12
  - fastapi
  - uvicorn
  - ffmpeg
  - librosa
  - numpy
  - scipy
  - numba
  - SQLAlchemy
  - psycopg2-binary
  - pydantic-settings
  - pip
  - scikit-learn
  - msaf
  - msaf[all]
  - pip:
    - soundfile