name: music-segmentation-worker-env
channels:
  - conda-forge
  - defaults
dependencies:
  - python=3.12
  - ffmpeg
  - librosa
  - numpy
  - scipy
  - numba
  - scikit-learn
  - pika
  - pip
  - pip:
    - msaf
    - msaf[all]
    - soundfile